name: Linters

on: pull_request

jobs:
  rubocop:
    name: RuboCop
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ">=3.1.x"
      - name: Install RuboCop and Configuration
        run: |
          gem install --no-document rubocop -v '>= 1.0, < 2.0'
          [ -f .rubocop.yml ] || wget https://raw.githubusercontent.com/microverseinc/linters-config/master/ruby/.rubocop.yml
      - name: RuboCop Report
        run: rubocop --color
      - name: Check RuboCop Installation
        run: rubocop --version
